import Head from "next/head";
import { useMyAppMedia } from "../hooks/useMyAppMedia";
import { FC } from "react";
import { Hero } from "../components/Hero/Hero";


const Home: FC = () => {

  const {minMediaDesktop } = useMyAppMedia();

  return (
    <>
      <Head>
        <title>Home</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      {minMediaDesktop && <h4>hjvgjhhgjhgjhgjhghjgjhgjhghj</h4>}
    </>
  );
};

export default Home;
