import Head from 'next/head'
import { useMediaQuery } from 'usehooks-ts'
import { FC } from "react";




 const  Home: FC = () => {
//  const mediaTab = useMediaQuery('(min-width: 768px)')

  return (<>
      <Head>
        <title>Home</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
 </> )
}

export default Home;