import Head from 'next/head'
import Image from 'next/image'
import styles from '../styles/Home.module.css'
// import { useMediaQuery } from 'usehooks-ts'
import { FC } from "react";
import { Header } from '../components/Heder/Header';



 const  Home: FC = () => {
//  const mediaTab = useMediaQuery('(min-width: 768px)')

  return (
    <div className={styles.container}>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <Header/>
      <aside style={{width: "100px"}} >
        <header>Lorem ipsum, dolor sit amet consectetur adipisicing elit. Vel ab debitis sit provident veniam quod harum ratione eveniet accusamus nam!</header>
      <p>Lorem ipsum dolor sit amet consectetur adipisicing elit. Corporis quo cum explicabo similique. Voluptatibus unde tempora omnis possimus id voluptates consectetur maiores, veritatis fuga suscipit beatae repellendus soluta dolore! Cumque modi pariatur officia consequuntur necessitatibus rerum, unde hic eveniet enim neque beatae excepturi reiciendis soluta harum optio, perferendis corporis delectus!</p>
      </aside>

     
      <main className={styles.main}>
     <p>Lorem ipsum dolor, sit amet consectetur adipisicing elit. Et, numquam, voluptate ipsum natus facilis repellendus labore atque soluta quidem aut cumque eveniet distinctio ipsa? Nobis voluptate accusamus, eaque ut magni, voluptatem fugit dolorem harum, ea earum facilis deserunt beatae. Quae ipsum ex modi. Sequi culpa voluptatem, non omnis sed tempore fuga eius, iure voluptas totam saepe voluptatibus ipsa perferendis consequatur vero adipisci dolore possimus tenetur nobis facere! Quibusdam provident itaque corrupti facere corporis fuga vero molestias culpa ipsum explicabo temporibus sint, officia cupiditate nam ratione totam veritatis blanditiis, esse nesciunt. Natus rerum inventore quisquam quam, tenetur ad voluptates aperiam placeat?</p>
        
      </main>

     
    </div>
  )
}


export default Home;